/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface BoxFactoryInterface extends utils.Interface {
  functions: {
    "boxes(uint256)": FunctionFragment;
    "createNewBox(string)": FunctionFragment;
    "getAllBoxes()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "boxes" | "createNewBox" | "getAllBoxes"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "boxes",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createNewBox",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllBoxes",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "boxes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createNewBox",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllBoxes",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BoxFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BoxFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    boxes(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    createNewBox(
      _value: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAllBoxes(overrides?: CallOverrides): Promise<[string[]]>;
  };

  boxes(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  createNewBox(
    _value: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAllBoxes(overrides?: CallOverrides): Promise<string[]>;

  callStatic: {
    boxes(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    createNewBox(
      _value: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllBoxes(overrides?: CallOverrides): Promise<string[]>;
  };

  filters: {};

  estimateGas: {
    boxes(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createNewBox(
      _value: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAllBoxes(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    boxes(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createNewBox(
      _value: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAllBoxes(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
