/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as factoredBoxSol from "./FactoredBox.sol";
export type { factoredBoxSol };
import type * as verifyableBoxSol from "./VerifyableBox.sol";
export type { verifyableBoxSol };
import type * as test from "./test";
export type { test };
export type { AccessRolesBox } from "./AccessRolesBox";
export type { ColorBoxV1 } from "./ColorBoxV1";
export type { ColorBoxV2 } from "./ColorBoxV2";
export type { DaoNat } from "./DaoNat";
export type { DummyGovernor } from "./DummyGovernor";
export type { PausableBox } from "./PausableBox";
export type { RevertibleBox } from "./RevertibleBox";
export type { SolidityFeaturesContract } from "./SolidityFeaturesContract";
