/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BoxFactory__factory } from "./BoxFactory__factory";
export { FactoredBox__factory } from "./FactoredBox__factory";
